name:                HidatoGenerator
version:             0.1.0.0
github:              "ob-fun-ws18/studienarbeit-bugproducer"
license:             BSD3
author:              "Tripolt, Mark"
maintainer:          "example@example.com"
copyright:           "2018 Tripolt, Mark"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/HidatoGenerator#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  HidatoGenerator-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HidatoGenerator
    - matrix
    - random

tests:
  HidatoGenerator-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HidatoGenerator
    - matrix
    - random
